version: 0.2

phases:
    pre_build:
      commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    build:
      commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker network create kong-net
      - export TAG_TIMESTAMP=`date +%s`
      - docker-compose up -d
      - docker tag kong:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:kong-migration:-${TAG_TIMESTAMP}
      - docker tag kong:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:kong-${TAG_TIMESTAMP}
      - docker tag pantsel/konga:next $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:konga-${TAG_TIMESTAMP}
    post_build:
      commands:
        - echo Build completed on `date`
        - echo Pushing the Docker image...
         - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:kong-migration-${TAG_TIMESTAMP}
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:kong-${TAG_TIMESTAMP}
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:konga-${TAG_TIMESTAMP}
        - echo Writing image definitions file...
   #    - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI/$IMAGE_REPO_NAME:${TAG_TIMESTAMP} > imagedefinitions.json
        - printf '[{"name":"%s","imageUri":"%s"},{"name":"%s","imageUri":"%s"},{"name":"%s","imageUri":"%s"}]' kong-api-gateway $REPOSITORY_URI/$IMAGE_REPO_NAME:kong-${TAG_TIMESTAMP} kong-migration $REPOSITORY_URI/$IMAGE_REPO_NAME:kong-migration-${TAG_TIMESTAMP} konga $REPOSITORY_URI/$IMAGE_REPO_NAME:konga-${TAG_TIMESTAMP} > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
