version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export TAG_TIMESTAMP=`date +%s`
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - export TAG_TIMESTAMP=`date +%s`
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$TAG_TIMESTAMP -f ./Dockerfile --build-arg ENV=$ENV .
      - docker tag $IMAGE_REPO_NAME:$TAG_TIMESTAMP ${REPOSITORY_URI}/$IMAGE_REPO_NAME:${TAG_TIMESTAMP}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image....
      - docker push ${REPOSITORY_URI}/$IMAGE_REPO_NAME:${TAG_TIMESTAMP}
      - echo Writing image definitions file....
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME ${REPOSITORY_URI}/$IMAGE_REPO_NAME:${TAG_TIMESTAMP} > images.json
artifacts:
  files:
    - images.json
cache:
  paths:
    - '/tmp/.m2/**/*'
