version: "3"

networks:
 kong-net:
  driver: bridge

services:

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_USER: hipayadmin
      KONG_PG_HOST: 10.1.1.179
      KONG_PG_PORT: 5434
      KONG_PG_PASSWORD: hvWcwXMO65o6ICqb
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:next
    depends_on:
      - kong
    ports:
      - "1337:1337"
    environment:
      DB_ADAPTER: postgres
      DB_HOST: 10.1.1.179
      DB_PORT: 5434
      DB_USER: hipayadmin
      DB_PASSWORD: hvWcwXMO65o6ICqb
      DB_DATABASE: konga_db
      NODE_ENV: production
    networks:
      - kong-net


