version: "3"

networks:
 kong-net:
  driver: bridge

services:

  kong-migration:
    image: kong:latest
    command:
      - kong migrations bootstrap
      - kong migrations list
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong_dev
      KONG_PG_USER: hipayadmin
      KONG_PG_HOST: 10.1.1.179
      KONG_PG_PORT: 5434
      KONG_PG_PASSWORD: hvWcwXMO65o6ICqb

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong_dev
      KONG_PG_USER: hipayadmin
      KONG_PG_HOST: 10.1.1.179
      KONG_PG_PORT: 5434
      KONG_PG_PASSWORD: hvWcwXMO65o6ICqb
      KONG_PROXY_LISTEN: 8000
      KONG_PROXY_LISTEN_SSL: 8443
      KONG_ADMIN_LISTEN: 8001
      KONG_ADMIN_LISTEN_SSL: 8444
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:next
    depends_on:
      - kong
    ports:
      - "1337:1337"
    environment:
      DB_ADAPTER: postgres
      DB_HOST: 10.1.1.179
      DB_PORT: 5434
      DB_USER: hipayadmin
      DB_PASSWORD: hvWcwXMO65o6ICqb
      NODE_ENV: production
      DB_DATABASE: konga_db_dev
    networks:
      - kong-net

